package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"

	"github.com/pkg/errors"
)

// Generated by https://quicktype.io

type Users []User

type User struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Address  Address `json:"address"`
	Phone    string  `json:"phone"`
	Website  string  `json:"website"`
	Company  Company `json:"company"`
}

type Address struct {
	Street  string `json:"street"`
	Suite   string `json:"suite"`
	City    string `json:"city"`
	Zipcode string `json:"zipcode"`
	Geo     Geo    `json:"geo"`
}

type Geo struct {
	Lat string `json:"lat"`
	Lng string `json:"lng"`
}

type Company struct {
	Name        string `json:"name"`
	CatchPhrase string `json:"catchPhrase"`
	Bs          string `json:"bs"`
}

func main() {
	res, err := http.Get("https://jsonplaceholder.typicode.com/users")
	if err != nil {
		err = errors.Wrap(err, "error to get data from: https://jsonplaceholder.typicode.com/users")
		log.Fatal(err)
	}

	// body is streaming -> read & close
	defer res.Body.Close()

	var users Users

	r := json.NewDecoder(res.Body)
	err = r.Decode(&users)
	if err != nil {
		log.Fatal(err)
	}

	for _, users := range users {
		fmt.Println(users)
	}
}
